spring.application.name=course-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/courseDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=passwordc

#spring.datasource.url=jdbc:h2:mem:courseDB
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

student.service.base-url=${STUDENT_SERVICE_BASE_URL:http://localhost:9090}

logging.level.az.edu.ada.wm2.courseservice=DEBUG
logging.level.feign=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

feign.client.config.default.loggerLevel=full
